### ISSUE TITLE
Timer should check if TextView is null

### ISSUE THREAD

**Issue by dirkam** [yashovardhan99/TimeIt#13]
Thanks for this library.

I believe Timer should check if textview is null before displaying the text. Similar to Stopwatch.

This way it's not possible to use Timer without the textview and it also makes it hard to use the Timer in different scenarios.

Thanks.

**Comment by yashovardhan99** [comment]
Hi, Thanks a lot for opening the issue. This issue was fixed in #12. However, I didn't get time to release a new version. You can try using the timer directly from the master branch to solve your problem.
